### ISSUE TITLE
Is there an easier way? 

### ISSUE THREAD

**Issue by danielo515** [nolanlawson/pouchdb-replication-stream#33]
Hello, 

I just want to dump my database to a string. Is any easier solution than including two big libraries for this task? I don't need any Fs support or anything, just all the info inside a string. 

Thanks

**Comment by nolanlawson** [comment]
No, there's only [the method documented in the [readme](https://github.com/nolanlawson/pouchdb-replication-stream#dumping-to-a-string). If you would like to bundle it up into a plugin, though, I'd be happy to link to it from the README. :) It would probably save other people some time.

**Comment by danielo515** [comment]
Let's say I want to iterate over all the documents and build a JSON string myself. What should I include take in account to make it compatible with the load plugin?

**Comment by nolanlawson** [comment]
You should definitely not do that, because you will not build up the kind of doc objects that are suitable for replication. It's not enough to just do an `allDocs()`; the revision history (encoded in the `_revisions` object) also needs to be included.

I can understand the need for a client-side library that dumps to a string without requiring so many big dependencies, but right now you would probably have to fork `pouchdb-replication-stream` to accomplish that.

**Comment by danielo515** [comment]
> You should definitely not do that, because you will not build up the kind of doc objects that are suitable for replication.

I understand what you mean. But for my particular case (very, very particular) I think it's enough with a "normal" dump.

> I can understand the need for a client-side library that dumps to a string without requiring so many big dependencies,

As far as you understand the need I am fine with it. I definitively want to include that feature on my project, but I can wait until an easier (and lighter) solution is created. It's a nice feature, but it's not a deal breaker.

Regarding your comment on google groups_
> And FYI, I just checked using mingz , and it's only 44.5KB after uglification+minification. :)

I based my guessings on the minified version on the repo. Take in account that I have to include 145kb of pouch, 44.5kb of stream and I also have to include concat-stream, which I'm not sure how to do it because it's a node package. If you have any clue about this last point maybe I will try.

**Comment by nolanlawson** [comment]
http://wzrd.in can browserify any browserifiable node package, e.g.: https://wzrd.in/standalone/concat-stream@latest

To fork this repo and make it dump to a string, you can just modify [this function](https://github.com/nolanlawson/pouchdb-replication-stream/blob/ff46025a3129154b7ebd6063bcef7a57c01bf387/index.js#L27-L65) and instead of having it call `writableStream.write()`, you just concatenate a string.

Instead of forking, I would also support adding a `dumpToString()` function in this repo itself. Then we can just have a browserify build that builds without all the node `stream` dependencies.

**Comment by nolanlawson** [comment]
Hm, actually I'm wrong, you'd have to fork more than just that function. Maybe forking is the right approach.
