### ISSUE TITLE
Getting a GET request for Each Remote DB docs during the Streaming replication (browser side).

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/pouchdb-replication-stream#36]
Hello, 
I'm using the window.memorystream solution.
and on, dest.load(stream) :

I'm having a GET call for each DOCS 
![image](https://cloud.githubusercontent.com/assets/7273443/8954223/6f0d2d82-35e4-11e5-898f-8460f728375c.png)

This make the streaming very slow. Is there a way to get a whole bunch of docs into a single GET ?

Here is the Request of the Change : 
![image](https://cloud.githubusercontent.com/assets/7273443/8954265/b3603736-35e4-11e5-880c-2e8b233182e2.png)

And I'm getting a Get Call for each Docs : 
![image](https://cloud.githubusercontent.com/assets/7273443/8954304/ed4fc1a0-35e4-11e5-9eb9-f7efd3901b99.png)

**Comment by nolanlawson** [comment]
It sounds like the issue is that you are not using pouchdb-replication-stream. :) Having one request per document is a feature of normal PouchDB replication. Maybe you didn't use the `proxy` option to set a checkpoint, and so nothing is getting replicated via pouchdb-replication-stream, and when you switch over to normal replication it just starts from scratch?

**Comment by ronyrun** [comment]
I'm only using the pouchdb-replication-stream :


                  memoryStream = stream = null;
                    var memoryStream = window.memorystream;
                    var stream = new memoryStream();


                    $q.all([
                        factory.localDB.load(stream),
                        factory.remoteDB.dump(stream,factory.remoteSyncOption)
                    ]).then(function (result) {
                        console.debug('Hooray the stream replication is complete!', result); });

**Comment by ronyrun** [comment]
If I comment the dump line : 
// factory.remoteDB.dump(stream,factory.remoteSyncOption)
I dont have this behavior.

100% sure.

**Comment by ronyrun** [comment]
Here is the Option passed : 

remoteSyncOption : {
                live: true,
                retry : true,
                since : null,
                batch_size : 150,
                back_off_function: function (delay) {
                    if (!delay || delay === 0) {
                        return 1000;
                    }
                    return delay * 2;
                },
                filter : function(item) {
                    var type = factory.parse_id(item._id).type || item.type;
                    return type != 'forcedFreq'  && type != 'preference' && type != 'exchangeType' && type != '$email' && type !='relationstate';
                }
            }

**Comment by nolanlawson** [comment]
Oh right sorry, I see the issue.

The issue is that you are using pouchdb-replication-stream client-side. It is not really designed to be run that way if your goal is just faster replication.

By design you're supposed to call `.dump()` from the server-side (in a Node.js process) and then `load()` on the client-side using `pouchdb-load`. The whole "memorystream" thing is only designed for very particular use cases, e.g. people who are trying to replicate between two local databases or over bluetooth or something fancy like that.

You may want to look into [express-pouchdb-replication-stream](https://github.com/conor-mac-aoidh/express-pouchdb-replication-stream).
